# Version number
version: 0.2.0.{build}

# See http://www.appveyor.com/docs/appveyor-yml for many more options
environment:
  NugetApiKey:
    secure: j6GuCUpWeDI+J5F8eS5L8Y+ze5UCFw3f1+3/tbNahNriT7vwKoouMxCXpNF8MOvM

# Allow WMF5 (i.e. PowerShellGallery functionality)
image: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

# Disable automatic builds
build: false

# Only process these branches
branches:
  only:
  - master
  - development

# Invoke Pester to run all of the unit tests, then save the results into XML in order to populate the AppVeyor tests section
# If any of the tests fail, consider the pipeline failed
test_script:
- ps: . .\build.ps1
